export const pages = [
  {
    title: "Creating an account",
    keywords: ["account", "create", "signup", "register"],
    page: "/help/getting-started/creating-an-account",
    category: "Getting Started",
    featured: true,
  },
  {
    title: "Navigating the dashboard",
    keywords: ["dashboard", "navigate", "home"],
    page: "/help/getting-started/navigating-the-dashboard",
    category: "Getting Started",
    featured: true,
  },
  {
    title: "Managing friends and groups",
    keywords: ["friends", "chats", "groups", "create", "edit", "delete"],
    page: "/help/getting-started/managing-social",
    category: "Getting Started",
    featured: true,
  },
  {
    title: "Managing Schools",
    keywords: ["schools", "periods", "schedules", "create", "manage"],
    page: "/help/getting-started/managing-schools",
    category: "Getting Started",
    featured: false,
  },
  {
    title: "Coming across bugs and issues",
    keywords: ["bugs", "issues", "fix", "report", "contact", "support"],
    page: "/help/troubleshooting/bugs-and-issues",
    category: "Troubleshooting",
    featured: true,
  },
  {
    title: "Modifying schedules",
    keywords: ["schedules", "modify", "change", "classes", "periods", "slots"],
    page: "/help/troubleshooting/modifying-schedules",
    category: "Troubleshooting",
    featured: true,
  },
  {
    title: "Managing your account",
    keywords: ["account", "manage", "settings", "profile", "password"],
    page: "/help/troubleshooting/managing-account",
    category: "Troubleshooting",
    featured: true,
  },
  {
    title: "Page not loading",
    keywords: ["page", "loading", "not", "load", "error"],
    page: "/help/troubleshooting/page-not-loading",
    category: "Troubleshooting",
    featured: false,
  },
  {
    title:
      "Application error: a client-side error occured (see the browser console for more information).",
    keywords: ["application", "error", "client-side", "browser", "console"],
    page: "/help/troubleshooting/client-error",
    category: "Troubleshooting",
    featured: false,
  },
  {
    title: "Canvas needs Attention",
    keywords: [
      "canvas",
      "token",
      "invalid",
      "settings",
      "fix",
      "close",
      "account",
      "lock",
      "not",
      "dismissible",
    ],
    page: "/help/troubleshooting/canvas-needs-attention",
    category: "Troubleshooting",
    featured: false,
  },
  {
    title: "Modifying Canvas information and integrations",
    keywords: ["canvas", "modify", "change", "information", "integrations"],
    page: "/help/troubleshooting/canvas-integration",
    category: "Troubleshooting",
    featured: false,
  },
  {
    title: "Updating your payment information",
    keywords: [
      "payment",
      "update",
      "method",
      "credit",
      "card",
      "pro",
      "information",
    ],
    page: "/help/billing/update-details",
    category: "Billing",
    featured: true,
  },
  {
    title: "Canceling your subscription",
    keywords: ["cancel", "subscription", "pro", "plan", "delete"],
    page: "/help/billing/cancelling",
    category: "Billing",
    featured: true,
  },
  {
    title: "Currently released and planned features",
    keywords: ["features", "released", "planned", "coming", "soon"],
    page: "/help/billing/features",
    category: "Billing",
    featured: true,
  },
  {
    title: "Subscription not applied",
    keywords: ["subscription", "not", "applied", "pro", "plan"],
    page: "/help/billing/not-applied",
    category: "Billing",
    featured: false,
  },
  {
    title: "Joining the community",
    keywords: ["community", "join", "contribute", "share", "feedback"],
    page: "/help/community/joining",
    category: "Community",
    featured: true,
  },
  {
    title: "Sharing feedback",
    keywords: ["community", "feedback", "join", "contribute", "share"],
    page: "/help/community/feedback",
    category: "Community",
    featured: true,
  },
  {
    title: "Requesting a feature",
    keywords: ["community", "request", "feature", "join", "contribute"],
    page: "/help/community/requesting-features",
    category: "Community",
    featured: true,
  },
  {
    title: "Reporting a bug",
    keywords: ["community", "report", "bug", "join", "contribute"],
    page: "/help/community/reporting-bug",
    category: "Community",
    featured: false,
  },
];
